spring:
  application:
    name: e-commerce

  datasource:
    url: jdbc:mysql://localhost:3306/e_commerce?useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: beans, health, mappings
  endpoint:
    beans:
      enabled: true

jwt:
  signerKey: "6af1bf3113085cdd2b80529060f888899aedf307965920c68d6111c18f959558"